CREATE SEQUENCE SEQ_TIPO_RESIDUO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PONTO_COLETA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COLETA_REALIZADA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA_CAPACIDADE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONSOLIDADO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTIFICACAO START WITH 1 INCREMENT BY 1;

CREATE TABLE TIPO_RESIDUO (
    ID_TIPO NUMBER PRIMARY KEY,
    DESCRICAO VARCHAR2(50) NOT NULL,
    RECICLAVEL CHAR(1) CHECK (RECICLAVEL IN ('S', 'N')),
    PERIGOSO CHAR(1) CHECK (PERIGOSO IN ('S', 'N'))
);

CREATE TABLE PONTO_COLETA (
    ID_PONTO NUMBER PRIMARY KEY,
    ENDERECO VARCHAR2(100) NOT NULL,
    ID_TIPO NUMBER REFERENCES TIPO_RESIDUO(ID_TIPO),
    CAPACIDADE_MAX_KG NUMBER(10,2) NOT NULL,
    VOLUME_ATUAL_KG NUMBER(10,2) DEFAULT 0
);

CREATE TABLE COLETA_REALIZADA (
    ID_COLETA NUMBER PRIMARY KEY,
    ID_PONTO NUMBER REFERENCES PONTO_COLETA(ID_PONTO),
    DATA_COLETA DATE DEFAULT SYSDATE,
    PESO_RECOLHIDO_KG NUMBER(10,2) NOT NULL,
    EMPRESA_RESPONSAVEL VARCHAR2(50)
);

CREATE TABLE ALERTA_CAPACIDADE (
    ID_ALERTA NUMBER PRIMARY KEY,
    ID_PONTO NUMBER REFERENCES PONTO_COLETA(ID_PONTO),
    DATA_GERACAO DATE DEFAULT SYSDATE,
    MENSAGEM VARCHAR2(200),
    STATUS_RESOLVIDO CHAR(1) DEFAULT 'N' CHECK (STATUS_RESOLVIDO IN ('S', 'N'))
);

CREATE TABLE CONSOLIDADO_RECICLAGEM (
    ID_CONSOLIDADO NUMBER PRIMARY KEY,
    ID_TIPO NUMBER REFERENCES TIPO_RESIDUO(ID_TIPO),
    MES_ANO VARCHAR2(7),
    TOTAL_RECICLADO_KG NUMBER(12,2) DEFAULT 0
);

CREATE TABLE USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    SENHA_HASH VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER'
);

CREATE TABLE NOTIFICACAO (
    ID_NOTIFICACAO NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER REFERENCES USUARIO(ID_USUARIO),
    ID_PONTO NUMBER REFERENCES PONTO_COLETA(ID_PONTO),
    MENSAGEM VARCHAR2(300) NOT NULL,
    DATA_ENVIO DATE DEFAULT SYSDATE,
    LIDA CHAR(1) DEFAULT 'N' CHECK (LIDA IN ('S', 'N'))
);
