INSERT INTO TIPO_RESIDUO (ID_TIPO, DESCRICAO, RECICLAVEL, PERIGOSO) VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Plastico', 'S', 'N');
INSERT INTO TIPO_RESIDUO (ID_TIPO, DESCRICAO, RECICLAVEL, PERIGOSO) VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Papel', 'S', 'N');
INSERT INTO TIPO_RESIDUO (ID_TIPO, DESCRICAO, RECICLAVEL, PERIGOSO) VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Vidro', 'S', 'N');
INSERT INTO TIPO_RESIDUO (ID_TIPO, DESCRICAO, RECICLAVEL, PERIGOSO) VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Metal', 'S', 'N');
INSERT INTO TIPO_RESIDUO (ID_TIPO, DESCRICAO, RECICLAVEL, PERIGOSO) VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Eletronico', 'S', 'S');
INSERT INTO TIPO_RESIDUO (ID_TIPO, DESCRICAO, RECICLAVEL, PERIGOSO) VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Organico', 'N', 'N');
INSERT INTO TIPO_RESIDUO (ID_TIPO, DESCRICAO, RECICLAVEL, PERIGOSO) VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Quimico', 'N', 'S');

INSERT INTO PONTO_COLETA (ID_PONTO, ENDERECO, ID_TIPO, CAPACIDADE_MAX_KG, VOLUME_ATUAL_KG) VALUES (SEQ_PONTO_COLETA.NEXTVAL, 'Av. Paulista, 1000 - Sao Paulo/SP', 1, 500.00, 120.50);
INSERT INTO PONTO_COLETA (ID_PONTO, ENDERECO, ID_TIPO, CAPACIDADE_MAX_KG, VOLUME_ATUAL_KG) VALUES (SEQ_PONTO_COLETA.NEXTVAL, 'Rua das Flores, 250 - Campinas/SP', 2, 300.00, 80.00);
INSERT INTO PONTO_COLETA (ID_PONTO, ENDERECO, ID_TIPO, CAPACIDADE_MAX_KG, VOLUME_ATUAL_KG) VALUES (SEQ_PONTO_COLETA.NEXTVAL, 'Av. Brasil, 500 - Rio de Janeiro/RJ', 3, 600.00, 450.00);
INSERT INTO PONTO_COLETA (ID_PONTO, ENDERECO, ID_TIPO, CAPACIDADE_MAX_KG, VOLUME_ATUAL_KG) VALUES (SEQ_PONTO_COLETA.NEXTVAL, 'Rua XV de Novembro, 100 - Curitiba/PR', 4, 400.00, 60.00);
INSERT INTO PONTO_COLETA (ID_PONTO, ENDERECO, ID_TIPO, CAPACIDADE_MAX_KG, VOLUME_ATUAL_KG) VALUES (SEQ_PONTO_COLETA.NEXTVAL, 'Av. Sete de Setembro, 800 - Salvador/BA', 5, 200.00, 180.00);

INSERT INTO COLETA_REALIZADA (ID_COLETA, ID_PONTO, DATA_COLETA, PESO_RECOLHIDO_KG, EMPRESA_RESPONSAVEL) VALUES (SEQ_COLETA_REALIZADA.NEXTVAL, 1, TO_DATE('2025-09-15', 'YYYY-MM-DD'), 95.00, 'EcoRecicla LTDA');
INSERT INTO COLETA_REALIZADA (ID_COLETA, ID_PONTO, DATA_COLETA, PESO_RECOLHIDO_KG, EMPRESA_RESPONSAVEL) VALUES (SEQ_COLETA_REALIZADA.NEXTVAL, 2, TO_DATE('2025-09-20', 'YYYY-MM-DD'), 60.00, 'PapelVerde S.A.');
INSERT INTO COLETA_REALIZADA (ID_COLETA, ID_PONTO, DATA_COLETA, PESO_RECOLHIDO_KG, EMPRESA_RESPONSAVEL) VALUES (SEQ_COLETA_REALIZADA.NEXTVAL, 3, TO_DATE('2025-09-25', 'YYYY-MM-DD'), 320.00, 'VidroLimpo ME');
INSERT INTO COLETA_REALIZADA (ID_COLETA, ID_PONTO, DATA_COLETA, PESO_RECOLHIDO_KG, EMPRESA_RESPONSAVEL) VALUES (SEQ_COLETA_REALIZADA.NEXTVAL, 4, TO_DATE('2025-09-28', 'YYYY-MM-DD'), 50.00, 'MetalReciclados LTDA');
INSERT INTO COLETA_REALIZADA (ID_COLETA, ID_PONTO, DATA_COLETA, PESO_RECOLHIDO_KG, EMPRESA_RESPONSAVEL) VALUES (SEQ_COLETA_REALIZADA.NEXTVAL, 5, TO_DATE('2025-10-01', 'YYYY-MM-DD'), 150.00, 'GreenTech Coleta');

INSERT INTO ALERTA_CAPACIDADE (ID_ALERTA, ID_PONTO, DATA_GERACAO, MENSAGEM, STATUS_RESOLVIDO) VALUES (SEQ_ALERTA_CAPACIDADE.NEXTVAL, 3, TO_DATE('2025-09-24', 'YYYY-MM-DD'), 'ALERTA ESG: O ponto de coleta atingiu ou excedeu 90% de sua capacidade.', 'N');
INSERT INTO ALERTA_CAPACIDADE (ID_ALERTA, ID_PONTO, DATA_GERACAO, MENSAGEM, STATUS_RESOLVIDO) VALUES (SEQ_ALERTA_CAPACIDADE.NEXTVAL, 5, TO_DATE('2025-09-30', 'YYYY-MM-DD'), 'ALERTA ESG: O ponto de coleta atingiu ou excedeu 90% de sua capacidade.', 'N');

INSERT INTO CONSOLIDADO_RECICLAGEM (ID_CONSOLIDADO, ID_TIPO, MES_ANO, TOTAL_RECICLADO_KG) VALUES (SEQ_CONSOLIDADO.NEXTVAL, 1, '09/2025', 95.00);
INSERT INTO CONSOLIDADO_RECICLAGEM (ID_CONSOLIDADO, ID_TIPO, MES_ANO, TOTAL_RECICLADO_KG) VALUES (SEQ_CONSOLIDADO.NEXTVAL, 2, '09/2025', 60.00);
INSERT INTO CONSOLIDADO_RECICLAGEM (ID_CONSOLIDADO, ID_TIPO, MES_ANO, TOTAL_RECICLADO_KG) VALUES (SEQ_CONSOLIDADO.NEXTVAL, 3, '09/2025', 320.00);
INSERT INTO CONSOLIDADO_RECICLAGEM (ID_CONSOLIDADO, ID_TIPO, MES_ANO, TOTAL_RECICLADO_KG) VALUES (SEQ_CONSOLIDADO.NEXTVAL, 4, '09/2025', 50.00);
INSERT INTO CONSOLIDADO_RECICLAGEM (ID_CONSOLIDADO, ID_TIPO, MES_ANO, TOTAL_RECICLADO_KG) VALUES (SEQ_CONSOLIDADO.NEXTVAL, 5, '10/2025', 150.00);
